### ISSUE TITLE
Sponge

### ISSUE THREAD

**Issue by Shiemy** [X00LA/German-Spigot-Bukkit-Plugin-Translations#1]
Hey, unser Serveradmin nutzt Sponge und wollte gern die Files auf Deutsch haben, aber er hat nur die Datei: en_US2.conf und dort sind über 5000 Zeilen laut Notepad ++ und da zwischen 50 Zeilen immer mal 1 Satz zu finden is iwie komisch, daher meine frage können wir deine Datei irgendwie einfügen das es bei uns auch auf deutsch ist?

**Comment by X00LA** [comment]
Guten Morgen.
Erstmal vorweg. Auf Anfragen mit Hey und Co. Gehe ich nicht weiter ein und auf welche ohne ein Bitte schon 2 Mal nicht.
Bitte Anstand und Manieren lernen, dann Frage stellen.

Danke
